name: columnar_output
description: Provide formatted output in columns using Markdown or HTML.
version: 0.0.2
author: Ray Rischpater, KF6GPE <rischpater@google.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.17.3
